name: workflow_push_event
on: push
jobs:
  job_name_push:
    runs-on: ubuntu-latest
    steps:
      - name: output github data
        run: echo "${{toJson(github)}}"
      - name: clone the code
        uses: actions/checkout@v3
      - name: Installing Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying..."
